version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tap
    binary: tap
    main: ./cmd/tap
    env: [CGO_ENABLED=0, GOWORK=off]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags: ["-s -w"]
  - id: kegv2
    binary: kegv2
    main: ./cmd/kegv2
    env: [CGO_ENABLED=0, GOWORK=off]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags: ["-s -w"]

archives:
  - id: tap
    builds: [tap]
    name_template: "tap_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files: [LICENSE, README.md, CHANGELOG.md]
  - id: kegv2
    builds: [kegv2]
    name_template: "kegv2_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files: [LICENSE, README.md, CHANGELOG.md]

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true   # git-cliff owns the changelog

release:
  footer: |
    ---
    Released with [GoReleaser](https://goreleaser.com).
