# https://taskfile.dev

version: "3"

tasks:
  run: go run "./cmd/keg" {{.CLI_ARGS}}
  test:
    cmds:
      - go test ./pkg/... {{.CLI_ARGS}}
    sources:
      - ./pkg/**/*.go
      - ./doc/**/*.md
    silent: true
  install-keg:
    desc: Install the keg CLI (go install ./cmd/keg).
    cmds:
      - go install ./cmd/keg
    sources:
      - cmd/**
      - pkg/**
      - docs/**/*.md
  install-tap:
    desc: Install the tap CLI (go install ./cmd/tap).
    cmds:
      - go install ./cmd/tap
    sources:
      - cmd/**/*.go
      - pkg/**/*.go
      - docs/**/*.md
